# Generated by Django 3.1.4 on 2020-12-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201204_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descripion',
            new_name='description',
        ),
    ]
